//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyingInfo
    {
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string Designation { get; set; }
        public string Company { get; set; }
        public string CaptchaCode { get; set; }
        public string CustomerMessage { get; set; }
        public string Country { get; set; }
        public string PhoneNumber { get; set; }
        public decimal Price { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public string Zipcode { get; set; }
        public string Paymentmode { get; set; }
        public string AreaCode { get; set; }
        public string IPAddress { get; set; }
        public string GuId { get; set; }
        public string ReportUrl { get; set; }
        public string TransactionId { get; set; }
        public string ReportTitle { get; set; }
        public int ReportId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> PaymentTransaction { get; set; }
        public string ErrorReason { get; set; }
        public string ErrorCode { get; set; }
        public string PayerId { get; set; }
        public string Token { get; set; }
        public string ACK { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string PaymentId { get; set; }
        public string Intent { get; set; }
        public string ReturnUrl { get; set; }
        public string PaymentStatus { get; set; }
    }
}
