//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsMaster
    {
        public int NewsId { get; set; }
        public string NewsTitle { get; set; }
        public string NewsUrl { get; set; }
        public int CategoryId { get; set; }
        public string NewsImage { get; set; }
        public string NewsDescription { get; set; }
        public System.DateTime PublishingDate { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescritpion { get; set; }
        public string Keywords { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
