//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublisherMaster
    {
        public int PublisherId { get; set; }
        public string PublisherName { get; set; }
        public string Address { get; set; }
        public string PublisherContactNumber { get; set; }
        public string publisherUrl { get; set; }
        public string Keywords { get; set; }
        public string LongDescription { get; set; }
        public string ShortDescription { get; set; }
        public string MetaDescription { get; set; }
        public string ContactName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsValid { get; set; }
    }
}
