//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMaster
    {
        public int ReportId { get; set; }
        public string ReportTitle { get; set; }
        public string ReportUrl { get; set; }
        public int CategoryId { get; set; }
        public int PublishereId { get; set; }
        public System.DateTime PublishingDate { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string Keywords { get; set; }
        public decimal SinglePrice { get; set; }
        public Nullable<decimal> MultiUserPrice { get; set; }
        public Nullable<decimal> CorporateUserPrice { get; set; }
        public string Domain { get; set; }
        public int ReportDeliveryTypeId { get; set; }
        public int ReportTypeId { get; set; }
        public string ReportImage { get; set; }
        public int NumberOfPages { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescritpion { get; set; }
        public string TableOfContent { get; set; }
        public string ListOfCharts { get; set; }
        public string ListOfFigure { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
