//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleActionRelation
    {
        public int RAId { get; set; }
        public int RId { get; set; }
        public int AId { get; set; }
    }
}
